// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOBTFFSJ0odn4zUMiB0pUgx9lvizZJjJo',
    appId: '1:618759759377:web:a52d8b5c3dd2207561f3b0',
    messagingSenderId: '618759759377',
    projectId: 'learnex-e91fd',
    authDomain: 'learnex-e91fd.firebaseapp.com',
    storageBucket: 'learnex-e91fd.firebasestorage.app',
    measurementId: 'G-FK9JDN9LE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsyhlRe4PkmTSAP6BWB2tDOo5AF08E4h0',
    appId: '1:618759759377:android:dde3485c811e9c1961f3b0',
    messagingSenderId: '618759759377',
    projectId: 'learnex-e91fd',
    storageBucket: 'learnex-e91fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIFHXaIDhysgb5fCs7cD6GYbUYaC0fLGk',
    appId: '1:618759759377:ios:8a557e5fc46a1d8261f3b0',
    messagingSenderId: '618759759377',
    projectId: 'learnex-e91fd',
    storageBucket: 'learnex-e91fd.firebasestorage.app',
    iosBundleId: 'com.learnex.learnex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIFHXaIDhysgb5fCs7cD6GYbUYaC0fLGk',
    appId: '1:618759759377:ios:8a557e5fc46a1d8261f3b0',
    messagingSenderId: '618759759377',
    projectId: 'learnex-e91fd',
    storageBucket: 'learnex-e91fd.firebasestorage.app',
    iosBundleId: 'com.learnex.learnex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOBTFFSJ0odn4zUMiB0pUgx9lvizZJjJo',
    appId: '1:618759759377:web:782ecbf8c8da8fd461f3b0',
    messagingSenderId: '618759759377',
    projectId: 'learnex-e91fd',
    authDomain: 'learnex-e91fd.firebaseapp.com',
    storageBucket: 'learnex-e91fd.firebasestorage.app',
    measurementId: 'G-094VXEN1PE',
  );
}
